const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const optionsV1 = {
  swaggerDefinition : {
    info: {
      title: 'RisePath CRM',
      version: '1.0',
      description: 'General REST APIs with autogenerated swagger doc',
    },
    basePath: "/api",
    securityDefinitions: {
      auth: {
        type: 'apiKey',
        description: 'JWT authorization of an API',
        name: 'Authorization',
        in: 'header',
      }
    },
    security: [
      { auth: [] }
    ]
  },
  // List of files to be processes. 
  apis: ['./docs/*.yaml'],
  
};

const optionsV2 = {
  swaggerDefinition : {
    info: {
      title: 'RisePath CRM',
      version: '1.0',
      description: 'General REST APIs with autogenerated swagger doc',
    },
    basePath: "/api",
    securityDefinitions: {
      auth: {
        type: 'apiKey',
        description: 'JWT authorization of an API',
        name: 'Authorization',
        in: 'header',
      }
    },
    security: [
      { auth: [] }
    ]
  },
  // List of files to be processes. 
  apis: ['./docs/support/*.yaml'],
};
const swaggerSpecV1 = swaggerJsdoc(optionsV1);
const swaggerSpecV2 = swaggerJsdoc(optionsV2);
const swaggerHtmlV1 = swaggerUi.generateHTML(swaggerSpecV1, optionsV1)
var swaggerHtmlV2 = swaggerUi.generateHTML(swaggerSpecV2, optionsV2)
module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serveFiles(swaggerSpecV1, optionsV1))
    app.get('/api-docs', (req, res) => { res.send(swaggerHtmlV1) });

    app.use('/support/api-docs', swaggerUi.serveFiles(swaggerSpecV2, optionsV2))
    app.get('/support/api-docs', (req, res) => { res.send(swaggerHtmlV2) });
    
}
